### ISSUE TITLE
Mappa su Monithon.it non carica

### ISSUE THREAD

**Issue by sirmmo** [Monithon/Monithon-2.0#9]

**Comment by luigireggi** [comment]
abilitato SSL su https://www.monithon.it/ ma ancora la mappa non compare

**Comment by sirmmo** [comment]
passa l'embed a https://monithon.org/embed

**Comment by luigireggi** [comment]
non funzia uguale >> monithon.org refused to connect.


<iframe width='100%' height='730' frameborder='0' src='https://monithon.org/embed' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

**Comment by sirmmo** [comment]
aggiunto anche altri header, puoi provare ora? se continua a non funzionare forziamo proprio la mano.

**Comment by luigireggi** [comment]
Non funzia
